[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "open_sem"
authors = [{name = "snowxwang", email = "snow.xwang@gmail.com"}]
dynamic = ["version", "description"]
